# Generated by Django 5.1.15 on 2026-06-14 14:54

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0002_remove_bingousertask_photo_proof_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bingousertask",
            name="photo_proof",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                null=True,
                quality=85,
                scale=None,
                size=[1024, 1024],
                upload_to="bingo_photos/",
            ),
        ),
    ]
